"""Phase names, legal transitions, weights, and the nginx conf renderer.

``deploy/nginx_canary.conf`` is *generated*, not hand-edited: it is the rollout's
only lever on live traffic, and a hand-edited conf is how a "rollback" quietly
becomes a no-op.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

_PHASES = ("shadow", "canary-5", "canary-25", "canary-50", "full")

# The only legal transitions. ``advance --to X`` must name exactly the edge
# out of the current phase.
_EDGES = {
    "shadow": "canary-5",
    "canary-5": "canary-25",
    "canary-25": "canary-50",
    "canary-50": "full",
}

_STABLE_UPSTREAM = "server raay-sentiment:3000"
_CANDIDATE_UPSTREAM = "server raay-sentiment-canary:3000"


def _weights_for(phase: str) -> tuple[int, int]:
    return {
        "shadow": (100, 0),
        "canary-5": (95, 5),
        "canary-25": (75, 25),
        "canary-50": (50, 50),
        "full": (0, 100),
        "rollback": (100, 0),
    }[phase]


def render_canary_conf(phase: str) -> str:
    """Render the nginx conf for a rollout stage.

    ``shadow`` mirrors every ``/predict`` to the candidate via ``/shadow`` and
    marks **both** hops ``X-Raay-Shadow: 1`` so the agent expects a pair.
    Every later phase drops the mirror entirely -- agreement needs the mirror
    by construction. The two locations that proxy to the candidate never touch
    ``$request_id``: a mirror subrequest is a separate request object, so its
    ``$request_id`` differs from the main request's, and ``proxy_set_header``
    on the main location is invisible to the mirror (nginx clones only the
    client-sent headers). Correlation therefore happens in the agent on the
    request content, which the mirror does clone.
    """
    stable_weight, candidate_weight = _weights_for(phase)
    mirrored = phase == "shadow"

    predict_hops = [
        "        proxy_pass http://raay_sentiment_backend/predict;",
        "        proxy_set_header Host $host;",
        "        proxy_set_header X-Real-IP $remote_addr;",
        "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
    ]
    if mirrored:
        predict_hops.append("        proxy_set_header X-Raay-Shadow 1;")
        predict_hops.append("        mirror /shadow;")

    shadow_block = ""
    if mirrored:
        shadow_block = (
            "    location /shadow {\n"
            "        proxy_pass http://raay-sentiment-canary:3000/predict;\n"
            "        proxy_set_header Host $host;\n"
            "        proxy_set_header X-Raay-Shadow 1;\n"
            "    }\n\n"
        )

    return (
        "# Phase 5 step 5 -- nginx front for the shadow/canary rollout.\n"
        "# Generated by scripts/canary_promote.py -- do not hand-edit.\n"
        f"# Stage: {phase} (stable={stable_weight}, candidate={candidate_weight}, "
        f"mirror={'yes' if mirrored else 'no'})\n\n"
        "upstream raay_sentiment_backend {\n"
        f"    {_STABLE_UPSTREAM} weight={stable_weight};\n"
        f"    {_CANDIDATE_UPSTREAM} weight={candidate_weight};\n"
        "}\n\n"
        "server {\n"
        "    listen 8000;\n"
        "    listen 8081;\n\n"
        "    location /predict {\n"
        + "\n".join(predict_hops)
        + "\n    }\n\n"
        + shadow_block
        + "    location /health {\n"
        "        proxy_pass http://raay_sentiment_backend/health;\n"
        "        proxy_set_header Host $host;\n"
        "    }\n"
        "}\n"
    )


@dataclass
class CanaryState:
    """Owned by the rollout: phase, candidate, pre-rollout Production, gates."""

    phase: str
    candidate_version: int
    previous_production_version: int | None
    entered_at: str
    prometheus_url: str
    last_gate: dict[str, Any] | None = None
    edges: list[dict[str, Any]] = field(default_factory=list)
